---
- name: Install stow
  become: true
  pacman:
    name: stow
  tags:
    - install
    - dotfiles

- name: Cloning dotfiles
  git:
    repo: git@github.com:r3k4mn14r/dotfiles.git
    dest: "{{ user_home }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    key_file: "{{ user_home }}/.ssh/ansible_personal"
    version: master
  tags:
    - install
    - dotfiles

- name: Unlinking previous dotfiles
  command: "stow -D -t {{ user_home }} -d {{ user_home }}/.dotfiles {{ item }}"
  with_items:
    - term
    - zsh
    - tmux
    - nvim
    - ipython
    - sway
    - waybar
    - swaylock
    - alacritty
  tags:
    - install
    - dotfiles

- name: Linking dotfiles
  command: "stow -t {{ user_home }} -d {{ user_home }}/.dotfiles {{ item }}"
  with_items:
    - term
    - zsh
    - tmux
    - nvim
    - ipython
    - sway
    - waybar
    - swaylock
    - alacritty
  tags:
    - install
    - dotfiles
