- name: Install laptop only packages
  become: true
  pacman:
    name:
      - amd-ucode
      - power-profiles-daemon
      - brightnessctl
      - bluez
      - linux-firmware
  tags:
    - laptop


- name: Enable Hardware Services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - power-profiles-daemon
    - bluetooth
  tags:
    - laptop
