---
- name: Ensure .ssh directory exists
  file:
    dest: "{{ ssh_dest_dir }}"
    mode: 0700
    state: directory
  tags:
    - install
    - ssh

- name: Ensure .ssh/s directory exists
  file:
    dest: "{{ ssh_dest_dir }}/s"
    mode: 0700
    state: directory
  tags:
    - install
    - ssh

- name: Install ssh key
  copy:
    src: "{{ ssh_key_source }}"
    dest: "{{ ssh_key_dest }}"
    mode: 0600
  tags:
    - install
    - ssh

- name: Install ssh key public
  copy:
    src: "{{ ssh_key_source }}.pub"
    dest: "{{ ssh_key_dest }}.pub"
    mode: 0644
  tags:
    - install
    - ssh

- name: Set authorized key from file
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', ssh_key_source + '.pub') }}"
  tags:
    - install
    - ssh

- name: Install ssh config
  copy:
    src: "{{ ssh_source_dir }}/config"
    dest: "{{ ssh_dest_dir }}/config"
    mode: 0600
  tags:
    - install
    - ssh
