- name: Setup dev tools
  become: true
  pacman: 
    name:
      - tmux
      - less
      - tldr
      - ripgrep
      - fd
      - git
      - bat
      - npm
      - btop
      - eza
      - unzip
      - wget
    state: present
  tags:
    - install
    - tools
