- name: Setup dev tools
  become: true
  pacman: 
    name:
      - tmux
      - tldr
      - ripgrep
      - fd
      - xclip
      - git
      - bat
      - alacritty
      - npm
      - btop
      - eza
  tags:
    - install
    - tools
